### ISSUE TITLE
documentation cannot be generated

### ISSUE THREAD

**Issue by ZeroSebastian** [chipsalliance/rocket-chip#3310]
**Type of issue**: bug report 

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
`sbt` in root directory, then `docs/mdoc`

**What is the current behavior?**
I tried to generate the documentation for Rocket Chip generator, however it always fails. I tried it with the latest master commit (at the time of creating this issue, which is `4fbd2f2`) but I also tried it with v1.6 tag. 
However, the error messages are different. I include them both in here:
Error message for master `4fbd2f2`:
```
...
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:39:8: not found: value chipsalliance
import chipsalliance.rocketchip.config.{Config, Parameters}
       ^^^^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:102:51: not found: type Parameters
  def edge(pd: DownwardParam, pu: UpwardParam, p: Parameters, sourceInfo: SourceInfo) = {
                                                  ^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:198:25: not found: type Parameters
class Adder(implicit p: Parameters) extends LazyModule {
                        ^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:198:22: could not find implicit value for parameter p: org.chipsalliance.cde.config.Parameters
class Adder(implicit p: Parameters) extends LazyModule {
                     ^^^^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:224:60: not found: type Parameters
class AdderDriver(width: Int, numOutputs: Int)(implicit p: Parameters) extends LazyModule {
                                                           ^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:224:19: could not find implicit value for parameter p: org.chipsalliance.cde.config.Parameters
class AdderDriver(width: Int, numOutputs: Int)(implicit p: Parameters) extends LazyModule {
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:251:62: not found: type Parameters
class AdderMonitor(width: Int, numOperands: Int)(implicit p: Parameters) extends LazyModule {
                                                             ^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:251:20: could not find implicit value for parameter p: org.chipsalliance.cde.config.Parameters
class AdderMonitor(width: Int, numOperands: Int)(implicit p: Parameters) extends LazyModule {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:283:38: not found: type Parameters
class AdderTestHarness()(implicit p: Parameters) extends LazyModule {
                                     ^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:283:35: could not find implicit value for parameter p: org.chipsalliance.cde.config.Parameters
class AdderTestHarness()(implicit p: Parameters) extends LazyModule {
                                  ^^^^^^^^^^^^^
error: /home/wsl_user/test/rocket-chip/docs/src/diplomacy/adder_tutorial.md:316:37: not found: value Parameters
  LazyModule(new AdderTestHarness()(Parameters.empty)).module
                                    ^^^^^^^^^^
info: Compiled in 3.67s (11 errors)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
[error] Nonzero exit code: 1
[error] (docs / Compile / runMain) Nonzero exit code: 1
[error] Total time: 143 s (02:23), completed Mar 15, 2023, 12:36:47 PM
sbt:rocketchip>
```

And the trace for v1.6:
```
...
[info] running mdoc.Main --cwd docs
[error] (run-main-0) java.lang.NoClassDefFoundError: scala/tools/nsc/reporters/AbstractReporter
[error] java.lang.NoClassDefFoundError: scala/tools/nsc/reporters/AbstractReporter
[error]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[error]         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error]         at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error]         at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]         at mdoc.internal.markdown.MarkdownBuilder$.fromClasspath(MarkdownBuilder.scala:92)
[error]         at mdoc.internal.cli.Context$.fromOptions(Context.scala:33)
[error]         at mdoc.internal.cli.Settings.validate(Settings.scala:231)
[error] Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.reporters.AbstractReporter
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[error]         at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[error]         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error]         at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error]         at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error] Nonzero exit code: 1
[error] (docs / Compile / runMain) Nonzero exit code: 1
[error] Total time: 145 s (02:25), completed Mar 15, 2023, 12:43:34 PM
sbt:rocketchip>
```
What else can I do to generate the documentation? I just want to make myself familiar with Rocket chip.

**What is the expected behavior?**
To generate the documentation.

**Please tell us about your environment:**
    - version: `4fbd2f2` (latest master), i also tried v1.6 release
    - OS: `Linux Ubuntu 22.04.2 LTS` running on WSL2
    - sbt 1.3.13

**Comment by michael-etzkorn** [comment]
Closed as repeat of #3230
