### ISSUE TITLE
Compile error on Chisel 6+ due to firrtl.options.RegisteredLibrary

### ISSUE THREAD

**Issue by tymcauley** [chipsalliance/rocket-chip#3579]
**Type of issue**: bug report

**Impact**: no functional change

**Development Phase**: proposal

**Other information**
 

When trying to build Rocket Chip with Chisel 6+, the following error is thrown:

```
java.util.ServiceConfigurationError: firrtl.options.RegisteredLibrary: Provider firrtl.passes.memlib.MemLibOptions not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at firrtl.options.Shell.registeredLibraries$lzycompute(Shell.scala:52)
        at firrtl.options.Shell.registeredLibraries(Shell.scala:49)
        at firrtl.options.Shell.parserSetup(Shell.scala:64)
        at firrtl.options.BareShell.parse(Shell.scala:33)
        at firrtl.options.Stage.execute(Stage.scala:56)
...
```

This is due to `src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary` containing the line `firrtl.passes.memlib.MemLibOptions`. This was added in #3260. If we remove that file, then this error goes away, but this will presumably cause issues with SFC compatibility. How do we want to handle this?

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Try to build Rocket Chip with Chisel 6+.

**What is the current behavior?**

Rocket Chip fails to compile on Chisel 6+.

**What is the expected behavior?**

Rocket Chip works on Chisel 6+.

**Please tell us about your environment:**
- version: current `dev` branch
- OS: macOS 14.3.1

**What is the use case for changing the behavior?**

Migrating to Chisel 6+.

**Comment by tymcauley** [comment]
Resolved by #3580.
